ERROR 2024-09-27 05:56:21,382 log Internal Server Error: /app/withdrawal/
Traceback (most recent call last):
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\exchangevista\app\views.py", line 1224, in withdrawal
    amount = Decimal(amount)
             ^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
ERROR 2024-09-27 05:56:21,394 log Internal Server Error: /app/withdrawal/
Traceback (most recent call last):
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\vista\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\achod\OneDrive\Desktop\Archive\brokers\exchange-vista\exchangevista\app\views.py", line 1224, in withdrawal
    amount = Decimal(amount)
             ^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
ERROR 2024-09-27 05:56:21,399 basehttp "POST /app/withdrawal/ HTTP/1.1" 500 79063
ERROR 2024-09-27 05:56:21,402 basehttp "POST /app/withdrawal/ HTTP/1.1" 500 79063
